/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  varchar,
  boolean,
  serial,
  timestamp,
  type AnyPgColumn,
  jsonb,
  numeric,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['ru', 'uz'])
export const enum_redirects_to_type = pgEnum('enum_redirects_to_type', ['reference', 'custom'])
export const enum_offices_items_region = pgEnum('enum_offices_items_region', [
  'tashkent',
  'tashkentRegion',
  'bukhara',
  'andijan',
  'samarkand',
  'navoiy',
  'jizzax',
  'qarshi',
  'termiz',
  'urganch',
  'karakalpakstan',
  'khorezm',
  'fergana',
  'surxondaryo',
  'sirdaryo',
  'namangan',
])

export const pages_blocks_about = pgTable(
  'pages_blocks_about',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_about_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_about_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_about_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_about_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_about_licenses = pgTable(
  'pages_blocks_about_licenses',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_about_licenses_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_about_licenses_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_about_licenses_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_about_licenses_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_additional_docs = pgTable(
  'pages_blocks_additional_docs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_additional_docs_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_additional_docs_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_additional_docs_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_additional_docs_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_archive = pgTable(
  'pages_blocks_archive',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_archive_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_archive_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_archive_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_archive_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_call_to_action = pgTable(
  'pages_blocks_call_to_action',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_call_to_action_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_call_to_action_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_call_to_action_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_call_to_action_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_employees = pgTable(
  'pages_blocks_employees',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_employees_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_employees_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_employees_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_employees_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_faq = pgTable(
  'pages_blocks_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    full: boolean('full'),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_faq_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_faq_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_faq_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_faq_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_hero = pgTable(
  'pages_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_hero_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_hero_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_hero_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_licenses = pgTable(
  'pages_blocks_licenses',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_licenses_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_licenses_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_licenses_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_licenses_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_map = pgTable(
  'pages_blocks_map',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_map_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_map_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_map_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_map_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_partners = pgTable(
  'pages_blocks_partners',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_partners_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_partners_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_partners_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_partners_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages_blocks_products = pgTable(
  'pages_blocks_products',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => ({
    _orderIdx: index('pages_blocks_products_order_idx').on(columns._order),
    _parentIDIdx: index('pages_blocks_products_parent_id_idx').on(columns._parentID),
    _pathIdx: index('pages_blocks_products_path_idx').on(columns._path),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_products_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    parent: integer('parent_id').references((): AnyPgColumn => pages.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug'),
    slugLock: boolean('slug_lock').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    pages_parent_idx: index('pages_parent_idx').on(columns.parent),
    pages_slug_idx: index('pages_slug_idx').on(columns.slug),
    pages_updated_at_idx: index('pages_updated_at_idx').on(columns.updatedAt),
    pages_created_at_idx: index('pages_created_at_idx').on(columns.createdAt),
  }),
)

export const pages_locales = pgTable(
  'pages_locales',
  {
    title: varchar('title').notNull(),
    meta_title: varchar('meta_title'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    meta_description: varchar('meta_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => ({
    pages_meta_meta_image_idx: index('pages_meta_meta_image_idx').on(
      columns.meta_image,
      columns._locale,
    ),
    _localeParent: uniqueIndex('pages_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt'),
    caption: jsonb('caption'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width'),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height'),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize'),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_square_url: varchar('sizes_square_url'),
    sizes_square_width: numeric('sizes_square_width'),
    sizes_square_height: numeric('sizes_square_height'),
    sizes_square_mimeType: varchar('sizes_square_mime_type'),
    sizes_square_filesize: numeric('sizes_square_filesize'),
    sizes_square_filename: varchar('sizes_square_filename'),
    sizes_small_url: varchar('sizes_small_url'),
    sizes_small_width: numeric('sizes_small_width'),
    sizes_small_height: numeric('sizes_small_height'),
    sizes_small_mimeType: varchar('sizes_small_mime_type'),
    sizes_small_filesize: numeric('sizes_small_filesize'),
    sizes_small_filename: varchar('sizes_small_filename'),
    sizes_medium_url: varchar('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width'),
    sizes_medium_height: numeric('sizes_medium_height'),
    sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize'),
    sizes_medium_filename: varchar('sizes_medium_filename'),
    sizes_large_url: varchar('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width'),
    sizes_large_height: numeric('sizes_large_height'),
    sizes_large_mimeType: varchar('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize'),
    sizes_large_filename: varchar('sizes_large_filename'),
    sizes_xlarge_url: varchar('sizes_xlarge_url'),
    sizes_xlarge_width: numeric('sizes_xlarge_width'),
    sizes_xlarge_height: numeric('sizes_xlarge_height'),
    sizes_xlarge_mimeType: varchar('sizes_xlarge_mime_type'),
    sizes_xlarge_filesize: numeric('sizes_xlarge_filesize'),
    sizes_xlarge_filename: varchar('sizes_xlarge_filename'),
    sizes_og_url: varchar('sizes_og_url'),
    sizes_og_width: numeric('sizes_og_width'),
    sizes_og_height: numeric('sizes_og_height'),
    sizes_og_mimeType: varchar('sizes_og_mime_type'),
    sizes_og_filesize: numeric('sizes_og_filesize'),
    sizes_og_filename: varchar('sizes_og_filename'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
    media_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      'media_sizes_thumbnail_sizes_thumbnail_filename_idx',
    ).on(columns.sizes_thumbnail_filename),
    media_sizes_square_sizes_square_filename_idx: index(
      'media_sizes_square_sizes_square_filename_idx',
    ).on(columns.sizes_square_filename),
    media_sizes_small_sizes_small_filename_idx: index(
      'media_sizes_small_sizes_small_filename_idx',
    ).on(columns.sizes_small_filename),
    media_sizes_medium_sizes_medium_filename_idx: index(
      'media_sizes_medium_sizes_medium_filename_idx',
    ).on(columns.sizes_medium_filename),
    media_sizes_large_sizes_large_filename_idx: index(
      'media_sizes_large_sizes_large_filename_idx',
    ).on(columns.sizes_large_filename),
    media_sizes_xlarge_sizes_xlarge_filename_idx: index(
      'media_sizes_xlarge_sizes_xlarge_filename_idx',
    ).on(columns.sizes_xlarge_filename),
    media_sizes_og_sizes_og_filename_idx: index('media_sizes_og_sizes_og_filename_idx').on(
      columns.sizes_og_filename,
    ),
  }),
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    heroImage: integer('hero_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    slug: varchar('slug'),
    slugLock: boolean('slug_lock').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    posts_hero_image_idx: index('posts_hero_image_idx').on(columns.heroImage),
    posts_slug_idx: index('posts_slug_idx').on(columns.slug),
    posts_updated_at_idx: index('posts_updated_at_idx').on(columns.updatedAt),
    posts_created_at_idx: index('posts_created_at_idx').on(columns.createdAt),
  }),
)

export const posts_locales = pgTable(
  'posts_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    content: jsonb('content').notNull(),
    meta_title: varchar('meta_title'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    meta_description: varchar('meta_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => ({
    posts_meta_meta_image_idx: index('posts_meta_meta_image_idx').on(
      columns.meta_image,
      columns._locale,
    ),
    _localeParent: uniqueIndex('posts_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const redirects = pgTable(
  'redirects',
  {
    id: serial('id').primaryKey(),
    from: varchar('from').notNull(),
    to_type: enum_redirects_to_type('to_type').default('reference'),
    to_url: varchar('to_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    redirects_from_idx: index('redirects_from_idx').on(columns.from),
    redirects_updated_at_idx: index('redirects_updated_at_idx').on(columns.updatedAt),
    redirects_created_at_idx: index('redirects_created_at_idx').on(columns.createdAt),
  }),
)

export const redirects_rels = pgTable(
  'redirects_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    pagesID: integer('pages_id'),
    postsID: integer('posts_id'),
  },
  (columns) => ({
    order: index('redirects_rels_order_idx').on(columns.order),
    parentIdx: index('redirects_rels_parent_idx').on(columns.parent),
    pathIdx: index('redirects_rels_path_idx').on(columns.path),
    redirects_rels_pages_id_idx: index('redirects_rels_pages_id_idx').on(columns.pagesID),
    redirects_rels_posts_id_idx: index('redirects_rels_posts_id_idx').on(columns.postsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [redirects.id],
      name: 'redirects_rels_parent_fk',
    }).onDelete('cascade'),
    pagesIdFk: foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'redirects_rels_pages_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'redirects_rels_posts_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    pagesID: integer('pages_id'),
    mediaID: integer('media_id'),
    usersID: integer('users_id'),
    postsID: integer('posts_id'),
    redirectsID: integer('redirects_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_pages_id_idx: index(
      'payload_locked_documents_rels_pages_id_idx',
    ).on(columns.pagesID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_posts_id_idx: index(
      'payload_locked_documents_rels_posts_id_idx',
    ).on(columns.postsID),
    payload_locked_documents_rels_redirects_id_idx: index(
      'payload_locked_documents_rels_redirects_id_idx',
    ).on(columns.redirectsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    pagesIdFk: foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    redirectsIdFk: foreignKey({
      columns: [columns['redirectsID']],
      foreignColumns: [redirects.id],
      name: 'payload_locked_documents_rels_redirects_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const header = pgTable('header', {
  id: serial('id').primaryKey(),
  telegram: varchar('telegram'),
  facebook: varchar('facebook'),
  instagram: varchar('instagram'),
  phone: varchar('phone').default('998 (90) 900-90-90'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const footer = pgTable('footer', {
  id: serial('id').primaryKey(),
  telegram: varchar('telegram'),
  facebook: varchar('facebook'),
  instagram: varchar('instagram'),
  email: varchar('email').default('Support@yniyat.uz'),
  phone: varchar('phone').default('998 (90) 900-90-90'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const footer_locales = pgTable(
  'footer_locales',
  {
    address: varchar('address').notNull().default('Ташкент, 9-й тупик Сагбан, 30'),
    copyright: varchar('copyright').notNull().default('ООО «CASH U mikromoliya tashkiloti»'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('footer_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const faq_items = pgTable(
  'faq_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => ({
    _orderIdx: index('faq_items_order_idx').on(columns._order),
    _parentIDIdx: index('faq_items_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [faq.id],
      name: 'faq_items_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const faq_items_locales = pgTable(
  'faq_items_locales',
  {
    title: varchar('title').notNull(),
    content: jsonb('content').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('faq_items_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [faq_items.id],
      name: 'faq_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const faq = pgTable('faq', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const partners_items = pgTable(
  'partners_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    media: integer('media_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => ({
    _orderIdx: index('partners_items_order_idx').on(columns._order),
    _parentIDIdx: index('partners_items_parent_id_idx').on(columns._parentID),
    partners_items_media_idx: index('partners_items_media_idx').on(columns.media),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [partners.id],
      name: 'partners_items_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const partners = pgTable('partners', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const offices_items_schedule = pgTable(
  'offices_items_schedule',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => ({
    _orderIdx: index('offices_items_schedule_order_idx').on(columns._order),
    _parentIDIdx: index('offices_items_schedule_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [offices_items.id],
      name: 'offices_items_schedule_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const offices_items_schedule_locales = pgTable(
  'offices_items_schedule_locales',
  {
    item: varchar('item').notNull().default('Пн-Сб с 09:00-18:00'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('offices_items_schedule_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [offices_items_schedule.id],
      name: 'offices_items_schedule_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const offices_items_phones = pgTable(
  'offices_items_phones',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    item: varchar('item').notNull().default('+998 (78) 113-31-11'),
  },
  (columns) => ({
    _orderIdx: index('offices_items_phones_order_idx').on(columns._order),
    _parentIDIdx: index('offices_items_phones_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [offices_items.id],
      name: 'offices_items_phones_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const offices_items = pgTable(
  'offices_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    region: enum_offices_items_region('region').default('tashkent'),
    media: integer('media_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => ({
    _orderIdx: index('offices_items_order_idx').on(columns._order),
    _parentIDIdx: index('offices_items_parent_id_idx').on(columns._parentID),
    offices_items_media_idx: index('offices_items_media_idx').on(columns.media),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [offices.id],
      name: 'offices_items_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const offices_items_locales = pgTable(
  'offices_items_locales',
  {
    title: varchar('title').notNull(),
    address: varchar('address').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('offices_items_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [offices_items.id],
      name: 'offices_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const offices = pgTable('offices', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const calc = pgTable('calc', {
  id: serial('id').primaryKey(),
  bez_zaloga_annualInterestRate: numeric('bez_zaloga_annual_interest_rate').notNull().default('80'),
  bez_zaloga_minTermMonths: numeric('bez_zaloga_min_term_months').notNull().default('6'),
  bez_zaloga_maxTermMonths: numeric('bez_zaloga_max_term_months').notNull().default('60'),
  bez_zaloga_minLoanAmount: numeric('bez_zaloga_min_loan_amount').notNull().default('1000000'),
  bez_zaloga_maxLoanAmount: numeric('bez_zaloga_max_loan_amount').notNull().default('100000000'),
  bez_zaloga_termMonths: numeric('bez_zaloga_term_months').notNull().default('6'),
  bez_zaloga_loanAmount: numeric('bez_zaloga_loan_amount').notNull().default('10000000'),
  pod_zalog_annualInterestRate: numeric('pod_zalog_annual_interest_rate').notNull().default('55'),
  pod_zalog_annualInterestRateGold: numeric('pod_zalog_annual_interest_rate_gold')
    .notNull()
    .default('80'),
  pod_zalog_minTermMonths: numeric('pod_zalog_min_term_months').notNull().default('6'),
  pod_zalog_maxTermMonths: numeric('pod_zalog_max_term_months').notNull().default('60'),
  pod_zalog_maxTermMonthsGold: numeric('pod_zalog_max_term_months_gold').notNull().default('12'),
  pod_zalog_minLoanAmount: numeric('pod_zalog_min_loan_amount').notNull().default('1000000'),
  pod_zalog_maxLoanAmount: numeric('pod_zalog_max_loan_amount').notNull().default('100000000'),
  pod_zalog_termMonths: numeric('pod_zalog_term_months').notNull().default('6'),
  pod_zalog_loanAmount: numeric('pod_zalog_loan_amount').notNull().default('10000000'),
  avtokredit_annualInterestRate: numeric('avtokredit_annual_interest_rate').notNull().default('54'),
  avtokredit_minTermMonths: numeric('avtokredit_min_term_months').notNull().default('6'),
  avtokredit_maxTermMonths: numeric('avtokredit_max_term_months').notNull().default('35'),
  avtokredit_minLoanAmount: numeric('avtokredit_min_loan_amount').notNull().default('1000000'),
  avtokredit_maxLoanAmount: numeric('avtokredit_max_loan_amount').notNull().default('100000000'),
  avtokredit_downPaymentPercent: numeric('avtokredit_down_payment_percent').notNull().default('20'),
  avtokredit_termMonths: numeric('avtokredit_term_months').notNull().default('6'),
  avtokredit_loanAmount: numeric('avtokredit_loan_amount').notNull().default('10000000'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_pages_blocks_about = relations(pages_blocks_about, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_about._parentID],
    references: [pages.id],
    relationName: '_blocks_about',
  }),
}))
export const relations_pages_blocks_about_licenses = relations(
  pages_blocks_about_licenses,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_about_licenses._parentID],
      references: [pages.id],
      relationName: '_blocks_aboutLicenses',
    }),
  }),
)
export const relations_pages_blocks_additional_docs = relations(
  pages_blocks_additional_docs,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_additional_docs._parentID],
      references: [pages.id],
      relationName: '_blocks_additionalDocs',
    }),
  }),
)
export const relations_pages_blocks_archive = relations(pages_blocks_archive, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_archive._parentID],
    references: [pages.id],
    relationName: '_blocks_archive',
  }),
}))
export const relations_pages_blocks_call_to_action = relations(
  pages_blocks_call_to_action,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_call_to_action._parentID],
      references: [pages.id],
      relationName: '_blocks_callToAction',
    }),
  }),
)
export const relations_pages_blocks_employees = relations(pages_blocks_employees, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_employees._parentID],
    references: [pages.id],
    relationName: '_blocks_employees',
  }),
}))
export const relations_pages_blocks_faq = relations(pages_blocks_faq, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_faq._parentID],
    references: [pages.id],
    relationName: '_blocks_faq',
  }),
}))
export const relations_pages_blocks_hero = relations(pages_blocks_hero, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_hero._parentID],
    references: [pages.id],
    relationName: '_blocks_hero',
  }),
}))
export const relations_pages_blocks_licenses = relations(pages_blocks_licenses, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_licenses._parentID],
    references: [pages.id],
    relationName: '_blocks_licenses',
  }),
}))
export const relations_pages_blocks_map = relations(pages_blocks_map, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_map._parentID],
    references: [pages.id],
    relationName: '_blocks_map',
  }),
}))
export const relations_pages_blocks_partners = relations(pages_blocks_partners, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_partners._parentID],
    references: [pages.id],
    relationName: '_blocks_partners',
  }),
}))
export const relations_pages_blocks_products = relations(pages_blocks_products, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_products._parentID],
    references: [pages.id],
    relationName: '_blocks_products',
  }),
}))
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: '_locales',
  }),
  meta_image: one(media, {
    fields: [pages_locales.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_pages = relations(pages, ({ one, many }) => ({
  _blocks_about: many(pages_blocks_about, {
    relationName: '_blocks_about',
  }),
  _blocks_aboutLicenses: many(pages_blocks_about_licenses, {
    relationName: '_blocks_aboutLicenses',
  }),
  _blocks_additionalDocs: many(pages_blocks_additional_docs, {
    relationName: '_blocks_additionalDocs',
  }),
  _blocks_archive: many(pages_blocks_archive, {
    relationName: '_blocks_archive',
  }),
  _blocks_callToAction: many(pages_blocks_call_to_action, {
    relationName: '_blocks_callToAction',
  }),
  _blocks_employees: many(pages_blocks_employees, {
    relationName: '_blocks_employees',
  }),
  _blocks_faq: many(pages_blocks_faq, {
    relationName: '_blocks_faq',
  }),
  _blocks_hero: many(pages_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_licenses: many(pages_blocks_licenses, {
    relationName: '_blocks_licenses',
  }),
  _blocks_map: many(pages_blocks_map, {
    relationName: '_blocks_map',
  }),
  _blocks_partners: many(pages_blocks_partners, {
    relationName: '_blocks_partners',
  }),
  _blocks_products: many(pages_blocks_products, {
    relationName: '_blocks_products',
  }),
  parent: one(pages, {
    fields: [pages.parent],
    references: [pages.id],
    relationName: 'parent',
  }),
  _locales: many(pages_locales, {
    relationName: '_locales',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_users = relations(users, () => ({}))
export const relations_posts_locales = relations(posts_locales, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_locales._parentID],
    references: [posts.id],
    relationName: '_locales',
  }),
  meta_image: one(media, {
    fields: [posts_locales.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  heroImage: one(media, {
    fields: [posts.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  _locales: many(posts_locales, {
    relationName: '_locales',
  }),
}))
export const relations_redirects_rels = relations(redirects_rels, ({ one }) => ({
  parent: one(redirects, {
    fields: [redirects_rels.parent],
    references: [redirects.id],
    relationName: '_rels',
  }),
  pagesID: one(pages, {
    fields: [redirects_rels.pagesID],
    references: [pages.id],
    relationName: 'pages',
  }),
  postsID: one(posts, {
    fields: [redirects_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
}))
export const relations_redirects = relations(redirects, ({ many }) => ({
  _rels: many(redirects_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    redirectsID: one(redirects, {
      fields: [payload_locked_documents_rels.redirectsID],
      references: [redirects.id],
      relationName: 'redirects',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_header = relations(header, () => ({}))
export const relations_footer_locales = relations(footer_locales, ({ one }) => ({
  _parentID: one(footer, {
    fields: [footer_locales._parentID],
    references: [footer.id],
    relationName: '_locales',
  }),
}))
export const relations_footer = relations(footer, ({ many }) => ({
  _locales: many(footer_locales, {
    relationName: '_locales',
  }),
}))
export const relations_faq_items_locales = relations(faq_items_locales, ({ one }) => ({
  _parentID: one(faq_items, {
    fields: [faq_items_locales._parentID],
    references: [faq_items.id],
    relationName: '_locales',
  }),
}))
export const relations_faq_items = relations(faq_items, ({ one, many }) => ({
  _parentID: one(faq, {
    fields: [faq_items._parentID],
    references: [faq.id],
    relationName: 'items',
  }),
  _locales: many(faq_items_locales, {
    relationName: '_locales',
  }),
}))
export const relations_faq = relations(faq, ({ many }) => ({
  items: many(faq_items, {
    relationName: 'items',
  }),
}))
export const relations_partners_items = relations(partners_items, ({ one }) => ({
  _parentID: one(partners, {
    fields: [partners_items._parentID],
    references: [partners.id],
    relationName: 'items',
  }),
  media: one(media, {
    fields: [partners_items.media],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_partners = relations(partners, ({ many }) => ({
  items: many(partners_items, {
    relationName: 'items',
  }),
}))
export const relations_offices_items_schedule_locales = relations(
  offices_items_schedule_locales,
  ({ one }) => ({
    _parentID: one(offices_items_schedule, {
      fields: [offices_items_schedule_locales._parentID],
      references: [offices_items_schedule.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_offices_items_schedule = relations(
  offices_items_schedule,
  ({ one, many }) => ({
    _parentID: one(offices_items, {
      fields: [offices_items_schedule._parentID],
      references: [offices_items.id],
      relationName: 'Schedule',
    }),
    _locales: many(offices_items_schedule_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_offices_items_phones = relations(offices_items_phones, ({ one }) => ({
  _parentID: one(offices_items, {
    fields: [offices_items_phones._parentID],
    references: [offices_items.id],
    relationName: 'phones',
  }),
}))
export const relations_offices_items_locales = relations(offices_items_locales, ({ one }) => ({
  _parentID: one(offices_items, {
    fields: [offices_items_locales._parentID],
    references: [offices_items.id],
    relationName: '_locales',
  }),
}))
export const relations_offices_items = relations(offices_items, ({ one, many }) => ({
  _parentID: one(offices, {
    fields: [offices_items._parentID],
    references: [offices.id],
    relationName: 'items',
  }),
  _locales: many(offices_items_locales, {
    relationName: '_locales',
  }),
  Schedule: many(offices_items_schedule, {
    relationName: 'Schedule',
  }),
  phones: many(offices_items_phones, {
    relationName: 'phones',
  }),
  media: one(media, {
    fields: [offices_items.media],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_offices = relations(offices, ({ many }) => ({
  items: many(offices_items, {
    relationName: 'items',
  }),
}))
export const relations_calc = relations(calc, () => ({}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_redirects_to_type: typeof enum_redirects_to_type
  enum_offices_items_region: typeof enum_offices_items_region
  pages_blocks_about: typeof pages_blocks_about
  pages_blocks_about_licenses: typeof pages_blocks_about_licenses
  pages_blocks_additional_docs: typeof pages_blocks_additional_docs
  pages_blocks_archive: typeof pages_blocks_archive
  pages_blocks_call_to_action: typeof pages_blocks_call_to_action
  pages_blocks_employees: typeof pages_blocks_employees
  pages_blocks_faq: typeof pages_blocks_faq
  pages_blocks_hero: typeof pages_blocks_hero
  pages_blocks_licenses: typeof pages_blocks_licenses
  pages_blocks_map: typeof pages_blocks_map
  pages_blocks_partners: typeof pages_blocks_partners
  pages_blocks_products: typeof pages_blocks_products
  pages: typeof pages
  pages_locales: typeof pages_locales
  media: typeof media
  users: typeof users
  posts: typeof posts
  posts_locales: typeof posts_locales
  redirects: typeof redirects
  redirects_rels: typeof redirects_rels
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  header: typeof header
  footer: typeof footer
  footer_locales: typeof footer_locales
  faq_items: typeof faq_items
  faq_items_locales: typeof faq_items_locales
  faq: typeof faq
  partners_items: typeof partners_items
  partners: typeof partners
  offices_items_schedule: typeof offices_items_schedule
  offices_items_schedule_locales: typeof offices_items_schedule_locales
  offices_items_phones: typeof offices_items_phones
  offices_items: typeof offices_items
  offices_items_locales: typeof offices_items_locales
  offices: typeof offices
  calc: typeof calc
  relations_pages_blocks_about: typeof relations_pages_blocks_about
  relations_pages_blocks_about_licenses: typeof relations_pages_blocks_about_licenses
  relations_pages_blocks_additional_docs: typeof relations_pages_blocks_additional_docs
  relations_pages_blocks_archive: typeof relations_pages_blocks_archive
  relations_pages_blocks_call_to_action: typeof relations_pages_blocks_call_to_action
  relations_pages_blocks_employees: typeof relations_pages_blocks_employees
  relations_pages_blocks_faq: typeof relations_pages_blocks_faq
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero
  relations_pages_blocks_licenses: typeof relations_pages_blocks_licenses
  relations_pages_blocks_map: typeof relations_pages_blocks_map
  relations_pages_blocks_partners: typeof relations_pages_blocks_partners
  relations_pages_blocks_products: typeof relations_pages_blocks_products
  relations_pages_locales: typeof relations_pages_locales
  relations_pages: typeof relations_pages
  relations_media: typeof relations_media
  relations_users: typeof relations_users
  relations_posts_locales: typeof relations_posts_locales
  relations_posts: typeof relations_posts
  relations_redirects_rels: typeof relations_redirects_rels
  relations_redirects: typeof relations_redirects
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_header: typeof relations_header
  relations_footer_locales: typeof relations_footer_locales
  relations_footer: typeof relations_footer
  relations_faq_items_locales: typeof relations_faq_items_locales
  relations_faq_items: typeof relations_faq_items
  relations_faq: typeof relations_faq
  relations_partners_items: typeof relations_partners_items
  relations_partners: typeof relations_partners
  relations_offices_items_schedule_locales: typeof relations_offices_items_schedule_locales
  relations_offices_items_schedule: typeof relations_offices_items_schedule
  relations_offices_items_phones: typeof relations_offices_items_phones
  relations_offices_items_locales: typeof relations_offices_items_locales
  relations_offices_items: typeof relations_offices_items
  relations_offices: typeof relations_offices
  relations_calc: typeof relations_calc
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
